### ISSUE TITLE
Import css files

### ISSUE THREAD

**Issue by vanbroup** [vanng822/go-premailer#1]
It would be useful if the package would automatically import local css files. This would really help to keep your source html template clean and to reuse the same style in multiple mail templates.

**Comment by vanng822** [comment]
Hi @vanbroup 

Thanks for the suggestion and sorry for the delay, I got stressed for sometimes and try not to do any unnecessary coding beside work.

I didn't about locale when I coded the package. The use case we had was that application rendering template which also import css and everything. I just assumed that most people do that way.

However remote and local would be nice to support. If you're interested please help out?

/VN

**Comment by vanng822** [comment]
One simple example that I did in am-lich.com project
```
  <head>
    <style>
    {{ template "css/common.css" }}
    {{ template "css/event.css" }}
    </style>
  </head>
```

**Comment by adueck** [comment]
When you do this, don't you have trouble with the `%` signs being escaped?

`width: 100%;` becomes `width: 100%!;(MISSING)` on render.

[This is what happens for me](https://stackoverflow.com/questions/55893056/escaping-percentage-signs-in-golang-html-templates). I have been doubling the `%`s to `%%`s in order for them to render normally but I wish there was a cleaner, more straightforward way...

**Comment by adueck** [comment]
@vanbroup Yes I @vanng822 's [suggestion](https://github.com/vanng822/go-premailer/issues/1#issuecomment-468405292) works great with [html/template](https://golang.org/pkg/html/template/) I found. 👍  I would suggest closing this issue.

**Comment by vanng822** [comment]
Seems that @vanbroup is not active.
I think that we should use the option available and keep the package simple. I close this for now
