### ISSUE TITLE
.content styles applied to <div class="content-wrap">

### ISSUE THREAD

**Issue by ajackson-cpi** [vanng822/go-premailer#3]
CSS styles I intended only for a 
  &lt;div class="content"&gt;
were also getting applied to a 
   &lt;div class="content-wrap"&gt;

My CSS rule was:
   .content {
      padding: 0;
   }

Workaround: Name no class a prefix of another (a common pattern though).

**Comment by vanng822** [comment]
Hi @ajackson-cpi Thanks for reporting.

Not sure I understand the problem. If it is a bug due to not well handling of name prefix or are you talking about css inheritance? If prefix problem then probably I can check and fix but inheritance is a big task.

**Comment by ajackson-cpi** [comment]
It’s a prefix problem. I suspect you match on substring instead of breaking the “class” list into tokens and comparing those.

**Comment by vanng822** [comment]
It is goquery that do jquery like dom search so probably bug somewhere there.

**Comment by vanng822** [comment]
Hi @ajackson-cpi Do you have a test case.
I tried this and worked fine

`<html>
        <head>
        <title>Title</title>
        <style type="text/css">
        .content {
        	padding: 0px;
        }
	.content-wrap {
        	padding: 2px;
        }
       	</style>
        </head>
        <body>
	    <div class="content-wrap">
	        <div class="content">
		    <strong>Yes!</strong>
		</div>
	   </div>
        </body>
        </html>`
