### ISSUE TITLE
Breaks Responsive Layout with Foundation for Emails

### ISSUE THREAD

**Issue by adueck** [vanng822/go-premailer#8]
I looove the idea of having an inliner available in GO. Thank you so much for writing this.

Unfortunately for me though, it doesn't work for inlining emails written with [Foundation for Emails]. 

Before inline:

<img width="489" alt="Screenshot 2019-04-26 15 12 21" src="https://user-images.githubusercontent.com/12955501/56804179-e5d4e180-6835-11e9-9fa1-32b812c16bcd.png">

After inline:  

<img width="484" alt="Screenshot 2019-04-26 15 12 30" src="https://user-images.githubusercontent.com/12955501/56804207-f38a6700-6835-11e9-95b5-1e339bd18e23.png">

It works fine when using another inliner, [inline-css](https://www.npmjs.com/package/inline-css) (with node), but somehow the inlining with with `go-premailier` is breaking it.

For a full example of the email and broken output:

[HTML with embedded CSS before inlining](https://gist.github.com/adueck/1b74efa6a5623dfbe5165ec1b2f74b8f)

[HTML after inlining with inline-css npm package](https://gist.github.com/adueck/723fa0a018421ffd976bd0661aa3427a) - This works 👍 

[HTML after inling with go-premailer](https://gist.github.com/adueck/fc3d2bec2d9d981525a91fa5240aa31b) - This is broken 😢 

I hope this is helpful... I would looove to be able to inline these in Go without having to do slow calls out to a separate node script.

Thanks!

**Comment by vanng822** [comment]
Thanks for reporting this issue!

This package has only basic functionalities and is not really matured since not many try it out.

After a quick look I see that "!important" is one of the difference(s).
I will take a close look later when I have time
Otherwise you can try and fix so it comes into the inline (probably somewhere in element.go)

**Comment by adueck** [comment]
Ya, thanks so much for having a look. 

Sorry I didn't dive deep into the differences, but I though the least I could do was offer the files. 🤔 

For now I'm using a really slow call out to a node script running inline-css, but it would be really awesome if this could get sorted and I'd use this. 👍 (Plus lots of others using Foundation hopefully)  

Another little issue I noticed is that it turns the `&nbsp;`s into spaces...

**Comment by adueck** [comment]
Oops didn't mean to hit the close button...

**Comment by adueck** [comment]
I should also mention that in order to get it to work with [inline-css](https://www.npmjs.com/package/inline-css) I needed to set the following options:

```
options.preserveMediaQueries = true;
options.applyTableAttributes = true;
```

> Whether to apply the `border`, `cellpadding` and `cellspacing` attributes to table elements.  

Is this the main problem? 🤔

**Comment by vanng822** [comment]
I found the problem. A sort causing that padding:0 is placed after paddin-* and override all.
I haven't looked into &nbsp; but probably has to do with github.com/PuerkitoBio/goquery hopefully that we can pass some flags to keep html entities. We should split up this into 2 issue. One with broken css-applied which I can fix as soon as possible

**Comment by vanng822** [comment]
Ok, the problem is bigger than I thought so it will take sometimes. I did a wrong assumption and have to redo both css and this packages to make css work better.

**Comment by vanng822** [comment]
I think your problem should be fixed.

Regarding the hard whitespace. I think goquery encodes it to hard whitespace according to unicode

Please try it out and confirm. You need to upgrade css as well

**Comment by adueck** [comment]
Great! Thanks so much. It seems to be working now except one other strange little bug that I can see...

When the email begins with a line (`<p></p>` or `<ul></li></li></ul>`) containing 3 (or sometimes 4) characters, it breaks the line like this: 

<img width="476" alt="Screenshot 2019-04-27 20 30 42" src="https://user-images.githubusercontent.com/12955501/56852349-77724b00-692b-11e9-934f-6f593786bebb.png">

Here the "H" in "<p>Hi,</p>" is floating on the right and to far over the container margin. 

[Email HTML Before Inlining](https://gist.github.com/adueck/079599e20edf36f0b7e620c639b0a5d3)

[Email HTML After go-premailer inlining](https://gist.github.com/adueck/46ca1e22ca24fad4dfedd6db8e682dc4) - Broken

[Email HTML After node inline-css](https://gist.github.com/adueck/29fff15992a7d45fb3318ec75322a50c) - Working 

How it looks with original HTML file and after node inline-css:

<img width="471" alt="Screenshot 2019-04-27 20 39 36" src="https://user-images.githubusercontent.com/12955501/56852445-a76e1e00-692c-11e9-8379-15e4d0cd64f5.png">

**Comment by vanng822** [comment]
What is your OS and browser. I don't have that issue on Mac (Firefox, Chrome, Opera). It looks like that the node version not the same as the original on my computer. Go version and original looks the same.

<img width="693" alt="Screenshot 2019-04-27 at 20 06 41" src="https://user-images.githubusercontent.com/1191756/56853430-1301bc80-6928-11e9-9ab1-8629009a409b.png">
<img width="712" alt="Screenshot 2019-04-27 at 20 06 51" src="https://user-images.githubusercontent.com/1191756/56853431-1301bc80-6928-11e9-9f45-9e6b335dcacd.png">
<img width="1045" alt="Screenshot 2019-04-27 at 20 07 05" src="https://user-images.githubusercontent.com/1191756/56853432-139a5300-6928-11e9-932e-949b2d44e859.png">

**Comment by vanng822** [comment]
I think the node version generate also invalid attribute such as width="100%%"
Another question is why do we have value in "100%%" ie 2 "%"

**Comment by adueck** [comment]
Sorry, something strange happened with the html files I saved...  Those are not right at all.

I also realized that the spacer table used at the beginning gets squished a little smaller in the `go-premailer` version. It might have something to do with that.

Don't have time now but a couple of days I will be able to give you proper html files and detailed examples. 

Thanks so much for your work on this. Would be great if this can become the go-to css inliner for GO. 👍 

(Also the double percentage thing could be from a different problem on my end... anyways, more in a couple of days!)

**Comment by adueck** [comment]
Ok, here are some proper examples

[Original File](https://gist.github.com/adueck/f20c1bc076db3d86c411a321e73f1777)

[After Inlining with inline-css](https://gist.github.com/adueck/d8ff04b5d349fc7d60d860019de203ae)

<img width="490" alt="ok" src="https://user-images.githubusercontent.com/12955501/56866597-19596c80-69ec-11e9-804f-9706c66e6201.PNG">

[After Inlining with go-premailer](https://gist.github.com/adueck/634c1e02f05ade1c88380211e7d98d35)

<img width="482" alt="broken" src="https://user-images.githubusercontent.com/12955501/56866600-1f4f4d80-69ec-11e9-85c5-dcb3b5af848a.PNG">

The inlining from go-premailer makes it look broken like this for Chrome on Windows (But not Firefox)

**Comment by vanng822** [comment]
Look like the problem is when converting to html-attribute of text-align and vertical-align.
It seems not an easy thing and probably time-consuming. I will remove that support (since there are recommendation not using it). Without align and valign, it looks quite good.

**Comment by vanng822** [comment]
Please give it a try and see if you are happy with the result.

I think the attribute conversion is complex so I will remove it complete in the future version. It should still work well for modern browsers

**Comment by adueck** [comment]
Thank you. With `option.CssToAttributes = false` that does look better now in my browser. 

As you mentioned: 

> It should still work well for modern browsers

However, *the problem with writing HTML/CSS for email clients is that you can't rely on modern browser standards.* Email clients are notorious for not supporting modern HTML5 features and to having bad compatibility, so you have to write *old style HTML*

https://www.campaignmonitor.com/css/

> Every single email client reading your email is going to have it's own rules about how it deals with HTML emails, so you are going to have to design for the lowest common denominator. Think it's a pain having to test websites in 4-5 different browsers? It's much worse with email. 

https://css-tricks.com/using-css-in-html-emails-the-real-story/

It may look good in the latest version of Chrome, but that's no guarantee that it will be production ready to send to all of different email clients that haven't been tested unfortunately.  

I'm really thankful for your work on this, and I would love for there to be something very reliable for Go. If you are able to work more on it, I'm sure it could be a huge use of a lot of people. 😃

**Comment by vanng822** [comment]
I hope that more people can help out. It started as a project to learn go and to prove that go can do faster than the python version (even I optimised the python version 5-10 times faster).

I have been using this for the latest 3 years but my css is to simple so that's why I never seen those bugs. Thanks for reporting.

**Comment by vanng822** [comment]
If you are happy for now please close the ticket. Let's see if there are some document how to map css to attributes. If you find one just notify me

**Comment by adueck** [comment]
Ok, I will close and see how things work out. Thank you for your help, and yes you're right Go can do it much much faster!

**Comment by vanng822** [comment]
No problem
